name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: luisarrabalgutierrez
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tutor-ai
            git reset --hard origin/main
            git pull origin main
            
            # actulizar python
            cd ~/tutor-ai/backend
            [ -d venv ] || python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            
            # reiniciar servicios
            pm2 restart backend || pm2 start "python3 -m uvicorn main:app --host 0.0.0.0 --port 8000" --name backend
            pm2 restart ngrok || pm2 start "ngrok http --domain=lunar-finicky-concierge.ngrok-free.dev 8000" --name ngrok
            
            pm2 save
            exit 0